const BASE_URL = "/api/users/";

const MANGA_TAGS = [
  "action",
  "adapation",
  "adventure",
  "animals",
  "bodyswap",
  "cars",
  "cheating",
  "childhood friends",
  "college life",
  "comedy",
  "cooking",
  "crime",
  "crossdressing",
  "delinquent",
  "dementia",
  "demons",
  "drama",
  "dungeons",
  "fantasy",
  "full color",
  "game",
  "gender bender",
  "ghosts",
  "gyaru",
  "harem",
  "historical",
  "horror",
  "isekai",
  "magic",
  "martial arts",
  "medical",
  "military",
  "monsters",
  "music",
  "mystery",
  "ninja",
  "office workers",
  "philosophical",
  "police",
  "post apocalypse",
  "psychological",
  "regression",
  "reincarnation",
  "reverse harem",
  "revenge",
  "reverse isekai",
  "romance",
  "royalty",
  "samurai",
  "school life",
  "sci-fi",
  "shota",
  "shoujo ai",
  "shounen ai",
  "showbiz",
  "slice of life",
  "space",
  "sports",
  "super power",
  "superhero",
  "supernatural",
  "survival",
  "thriller",
  "time travel",
  "tower climbing",
  "tragedy",
  "transmigration",
  "vampires",
  "villainess",
  "video game",
  "virtual reality",
  "wyxia",
  "xianxia",
  "xuanhuan",
  "yakuzas",
  "zombies",
];

export { BASE_URL, MANGA_TAGS };
