const BASE_URL = "/api/users/";

const MANGA_URL = "api/mangas";

const MANGA_TAGS = [
  "Action",
  "Adapation",
  "Adventure",
  "Animals",
  "Bodyswap",
  "Cars",
  "Cheating",
  "Childhood Friends",
  "College Life",
  "Comedy",
  "Cooking",
  "Crime",
  "Crossdressing",
  "Delinquent",
  "Dementia",
  "Demons",
  "Drama",
  "Dungeons",
  "Fantasy",
  "Full Color",
  "Game",
  "Gender Bender",
  "Ghosts",
  "Gyaru",
  "Harem",
  "Historical",
  "Horror",
  "Isekai",
  "Magic",
  "Martial Arts",
  "Medical",
  "Military",
  "Monsters",
  "Music",
  "Mystery",
  "Ninja",
  "Office Workers",
  "Philosophical",
  "Police",
  "Post Apocalypse",
  "Psychological",
  "Regression",
  "Reincarnation",
  "Reverse Harem",
  "Revenge",
  "Reverse Isekai",
  "Romance",
  "Royalty",
  "Samurai",
  "School Life",
  "Sci-Fi",
  "Shota",
  "Shoujo Ai",
  "Shounen Ai",
  "Showbiz",
  "Slice of Life",
  "Space",
  "Sports",
  "Super Power",
  "Superhero",
  "Supernatural",
  "Survival",
  "Thriller",
  "Time Travel",
  "Tower Climbing",
  "Tragedy",
  "Transmigration",
  "Vampires",
  "Villainess",
  "Video Game",
  "Virtual Reality",
  "Wuxia",
  "Xianxia",
  "Xuanhuan",
  "Yakuzas",
  "Zombies",
];

const MANGA_TYPE = [
  "manga",
  "manwha",
  "manhua",
  "webtoon",
  "comic",
  "western",
  "indie",
];

const COMIC_STATUS = ["ongoing", "completed", "hiatus", "dropped", "unknown"];

const READING_STATUS = [
  "reading",
  "completed",
  "on hold",
  "plan to read",
  "re-reading",
  "dropped",
];

export {
  BASE_URL,
  MANGA_TAGS,
  MANGA_TYPE,
  COMIC_STATUS,
  READING_STATUS,
  MANGA_URL,
};
